In [302]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [303]:
df_raw =pd.read_csv(r"C:\Users\HomePC\Desktop\EDA\train_features.csv")
df=df_raw.copy()
shape=df.shape
print(f" rows: {shape[0]}\n columns: {shape[1]}")

 rows: 59400
 columns: 40

In [304]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 40 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     59400 non-null  int64
 1   amount_tsh             59400 non-null  float64
 2   date_recorded          59400 non-null  str
 3   funder                 55763 non-null  str
 4   gps_height             59400 non-null  int64
 5   installer              55745 non-null  str
 6   longitude              59400 non-null  float64
 7   latitude               59400 non-null  float64
 8   wpt_name               59398 non-null  str
 9   num_private            59400 non-null  int64
 10  basin                  59400 non-null  str
 11  subvillage             59029 non-null  str
 12  region                 59400 non-null  str
 13  region_code            59400 non-null  int64
 14  district_code          59400 non-null  int64
 15  lga                    59400 non-null  str
 16  ward                   59400 non-null  str
 17  population             59400 non-null  int64
 18  public_meeting         56066 non-null  object
 19  recorded_by            59400 non-null  str
 20  scheme_management      55522 non-null  str
 21  scheme_name            30590 non-null  str
 22  permit                 56344 non-null  object
 23  construction_year      59400 non-null  int64
 24  extraction_type        59400 non-null  str
 25  extraction_type_group  59400 non-null  str
 26  extraction_type_class  59400 non-null  str
 27  management             59400 non-null  str
 28  management_group       59400 non-null  str
 29  payment                59400 non-null  str
 30  payment_type           59400 non-null  str
 31  water_quality          59400 non-null  str
 32  quality_group          59400 non-null  str
 33  quantity               59400 non-null  str
 34  quantity_group         59400 non-null  str
 35  source                 59400 non-null  str
 36  source_type            59400 non-null  str
 37  source_class           59400 non-null  str
 38  waterpoint_type        59400 non-null  str
 39  waterpoint_type_group  59400 non-null  str
dtypes: float64(3), int64(7), object(2), str(28)
memory usage: 32.2+ MB

In [305]:
df.dtypes

id                         int64
amount_tsh               float64
date_recorded                str
funder                       str
gps_height                 int64
installer                    str
longitude                float64
latitude                 float64
wpt_name                     str
num_private                int64
basin                        str
subvillage                   str
region                       str
region_code                int64
district_code              int64
lga                          str
ward                         str
population                 int64
public_meeting            object
recorded_by                  str
scheme_management            str
scheme_name                  str
permit                    object
construction_year          int64
extraction_type              str
extraction_type_group        str
extraction_type_class        str
management                   str
management_group             str
payment                      str
payment_type                 str
water_quality                str
quality_group                str
quantity                     str
quantity_group               str
source                       str
source_type                  str
source_class                 str
waterpoint_type              str
waterpoint_type_group        str
dtype: object

In [306]:
df.describe(include='number').T

,count,mean,std,min,25%,50%,75%,max
id,59400.0,37115.131768,21453.128371,0.00000,18519.750000,37061.500000,55656.500000,7.424700e+04
amount_tsh,59400.0,317.650385,2997.574558,0.00000,0.000000,0.000000,20.000000,3.500000e+05
gps_height,59400.0,668.297239,693.116350,-90.00000,0.000000,369.000000,1319.250000,2.770000e+03
longitude,59400.0,34.077427,6.567432,0.00000,33.090347,34.908743,37.178387,4.034519e+01
latitude,59400.0,-5.706033,2.946019,-11.64944,-8.540621,-5.021597,-3.326156,-2.000000e-08
num_private,59400.0,0.474141,12.236230,0.00000,0.000000,0.000000,0.000000,1.776000e+03
region_code,59400.0,15.297003,17.587406,1.00000,5.000000,12.000000,17.000000,9.900000e+01
district_code,59400.0,5.629747,9.633649,0.00000,2.000000,3.000000,5.000000,8.000000e+01
population,59400.0,179.909983,471.482176,0.00000,0.000000,25.000000,215.000000,3.050000e+04
construction_year,59400.0,1300.652475,951.620547,0.00000,0.000000,1986.000000,2004.000000,2.013000e+03

In [307]:
df.describe(include='object').T

                       count unique                      top   freq
date_recorded          59400    356               2011-03-15    572
funder                 55763   1896   Government Of Tanzania   9084
installer              55745   2145                      DWE  17402
wpt_name               59398  37399                     none   3563
basin                  59400      9            Lake Victoria  10248
subvillage             59029  19287                 Madukani    508
region                 59400     21                   Iringa   5294
lga                    59400    125                   Njombe   2503
ward                   59400   2092                    Igosi    307
public_meeting         56066      2                     True  51011
recorded_by            59400      1  GeoData Consultants Ltd  59400
scheme_management      55522     11                      VWC  36793
scheme_name            30590   2695                        K    682
permit                 56344      2                     True  38852
extraction_type        59400     18                  gravity  26780
extraction_type_group  59400     13                  gravity  26780
extraction_type_class  59400      7                  gravity  26780
management             59400     12                      vwc  40507
management_group       59400      5               user-group  52490
payment                59400      7                never pay  25348
payment_type           59400      7                never pay  25348
water_quality          59400      8                     soft  50818
quality_group          59400      6                     good  50818
quantity               59400      5                   enough  33186
quantity_group         59400      5                   enough  33186
source                 59400     10                   spring  17021
source_type            59400      7                   spring  17021
source_class           59400      3              groundwater  45794
waterpoint_type        59400      7       communal standpipe  28522
waterpoint_type_group  59400      6       communal standpipe  34625

In [308]:
# Unique value counts per column (helps spot ID-like vs categorical vs constant columns)
df.nunique().sort_values()

recorded_by                  1
public_meeting               2
permit                       2
source_class                 3
quantity                     5
quantity_group               5
management_group             5
quality_group                6
waterpoint_type_group        6
payment                      7
source_type                  7
waterpoint_type              7
payment_type                 7
extraction_type_class        7
water_quality                8
basin                        9
source                      10
scheme_management           11
management                  12
extraction_type_group       13
extraction_type             18
district_code               20
region                      21
region_code                 27
construction_year           55
num_private                 65
amount_tsh                  98
lga                        125
date_recorded              356
population                1049
funder                    1896
ward                      2092
installer                 2145
gps_height                2428
scheme_name               2695
subvillage               19287
wpt_name                 37399
longitude                57516
latitude                 57517
id                       59400
dtype: int64

In [309]:
# For low-cardinality object/bool-like columns, show the actual unique values
# (threshold of 20 is chosen to avoid dumping high-cardinality free-text columns like wpt_name)
for col in df.columns:
    if df[col].nunique() <= 20:
        print(f"--- {col} ({df[col].nunique()} unique) ---")
        print(df[col].unique())
        print()

--- basin (9 unique) ---
<ArrowStringArray>
[             'Lake Nyasa',           'Lake Victoria',
                 'Pangani', 'Ruvuma / Southern Coast',
                'Internal',         'Lake Tanganyika',
             'Wami / Ruvu',                  'Rufiji',
              'Lake Rukwa']
Length: 9, dtype: str

--- district_code (20 unique) ---
[ 5  2  4 63  1  8  3  6 43  7 23 33 53 62 60 30 13  0 80 67]

--- public_meeting (2 unique) ---
[True nan False]

--- recorded_by (1 unique) ---
<ArrowStringArray>
['GeoData Consultants Ltd']
Length: 1, dtype: str

--- scheme_management (11 unique) ---
<ArrowStringArray>
[             'VWC',            'Other',                nan,
 'Private operator',              'WUG',      'Water Board',
              'WUA',  'Water authority',          'Company',
       'Parastatal',            'Trust',              'SWC']
Length: 12, dtype: str

--- permit (2 unique) ---
[False True nan]

--- extraction_type (18 unique) ---
<ArrowStringArray>
[                  'gravity',               'submersible',
                    'swn 80',               'nira/tanira',
             'india mark ii',                     'other',
                       'ksb',                      'mono',
                  'windmill',                   'afridev',
         'other - rope pump',            'india mark iii',
            'other - swn 81',         'other - play pump',
                      'cemo',                    'climax',
                    'walimi', 'other - mkulima/shinyanga']
Length: 18, dtype: str

--- extraction_type_group (13 unique) ---
<ArrowStringArray>
[        'gravity',     'submersible',          'swn 80',     'nira/tanira',
   'india mark ii',           'other',            'mono',    'wind-powered',
         'afridev',       'rope pump',  'india mark iii',  'other handpump',
 'other motorpump']
Length: 13, dtype: str

--- extraction_type_class (7 unique) ---
<ArrowStringArray>
[     'gravity',  'submersible',     'handpump',        'other',
    'motorpump', 'wind-powered',    'rope pump']
Length: 7, dtype: str

--- management (12 unique) ---
<ArrowStringArray>
[             'vwc',              'wug',            'other',
 'private operator',      'water board',              'wua',
          'company',  'water authority',       'parastatal',
          'unknown',   'other - school',            'trust']
Length: 12, dtype: str

--- management_group (5 unique) ---
<ArrowStringArray>
['user-group', 'other', 'commercial', 'parastatal', 'unknown']
Length: 5, dtype: str

--- payment (7 unique) ---
<ArrowStringArray>
[         'pay annually',             'never pay',        'pay per bucket',
               'unknown', 'pay when scheme fails',                 'other',
           'pay monthly']
Length: 7, dtype: str

--- payment_type (7 unique) ---
<ArrowStringArray>
[  'annually',  'never pay', 'per bucket',    'unknown', 'on failure',
      'other',    'monthly']
Length: 7, dtype: str

--- water_quality (8 unique) ---
<ArrowStringArray>
[              'soft',              'salty',              'milky',
            'unknown',           'fluoride',           'coloured',
    'salty abandoned', 'fluoride abandoned']
Length: 8, dtype: str

--- quality_group (6 unique) ---
<ArrowStringArray>
['good', 'salty', 'milky', 'unknown', 'fluoride', 'colored']
Length: 6, dtype: str

--- quantity (5 unique) ---
<ArrowStringArray>
['enough', 'insufficient', 'dry', 'seasonal', 'unknown']
Length: 5, dtype: str

--- quantity_group (5 unique) ---
<ArrowStringArray>
['enough', 'insufficient', 'dry', 'seasonal', 'unknown']
Length: 5, dtype: str

--- source (10 unique) ---
<ArrowStringArray>
[              'spring', 'rainwater harvesting',                  'dam',
          'machine dbh',                'other',         'shallow well',
                'river',             'hand dtw',                 'lake',
              'unknown']
Length: 10, dtype: str

--- source_type (7 unique) ---
<ArrowStringArray>
[              'spring', 'rainwater harvesting',                  'dam',
             'borehole',                'other',         'shallow well',
           'river/lake']
Length: 7, dtype: str

--- source_class (3 unique) ---
<ArrowStringArray>
['groundwater', 'surface', 'unknown']
Length: 3, dtype: str

--- waterpoint_type (7 unique) ---
<ArrowStringArray>
[         'communal standpipe', 'communal standpipe multiple',
                   'hand pump',                       'other',
             'improved spring',               'cattle trough',
                         'dam']
Length: 7, dtype: str

--- waterpoint_type_group (6 unique) ---
<ArrowStringArray>
['communal standpipe',          'hand pump',              'other',
    'improved spring',      'cattle trough',                'dam']
Length: 6, dtype: str

In [310]:
# Missingness overview (raw, pre-standardization — real NaNs only at this point)
missing_df = (
    df.isnull().sum()
    .to_frame('missing_count')
    .assign(missing_pct=lambda x: (x['missing_count'] / len(df) * 100).round(3))
)
missing_df = missing_df[missing_df['missing_count'] > 0].sort_values('missing_pct', ascending=False)
print(missing_df)

                   missing_count  missing_pct
scheme_name                28810       48.502
scheme_management           3878        6.529
installer                   3655        6.153
funder                      3637        6.123
public_meeting              3334        5.613
permit                      3056        5.145
subvillage                   371        0.625
wpt_name                       2        0.003

In [311]:
#Duplicate check (it checks exact raw duplicates and duplicate IDs)
print(f"Exact duplicate rows: {df.duplicated().sum()}")
print(f"Duplicate IDs values: {df['id'].duplicated().sum()}")

Exact duplicate rows: 0
Duplicate IDs values: 0

In [312]:
#Standardize Missing-Value Markers

# ---  Audit: scan for common textual missing markers before touching anything ---
text_markers = {"na", "n/a", "unknown", "not known", "none", "-", "null", "nan", ""}

audit_rows = []
for col in df.select_dtypes(include="object").columns:
    vals = df[col].astype(str).str.strip().str.lower()
    hits = vals.isin(text_markers).sum()
    if hits > 0:
        audit_rows.append((col, hits, sorted(set(vals[vals.isin(text_markers)]))))

audit_df = pd.DataFrame(audit_rows, columns=["column", "marker_count", "markers_found"])
audit_df.sort_values("marker_count", ascending=False)

              column  marker_count               markers_found
7       payment_type          8157                   [unknown]
6            payment          8157                   [unknown]
2           wpt_name          3586  [none, not known, unknown]
8      water_quality          1876                   [unknown]
9      quality_group          1876                   [unknown]
10          quantity           789                   [unknown]
11    quantity_group           789                   [unknown]
4         management           561                   [unknown]
5   management_group           561                   [unknown]
13      source_class           278                   [unknown]
12            source            66                   [unknown]
1          installer            48     [-, not known, unknown]
3        scheme_name            33           [none, not known]
0             funder            31        [not known, unknown]

In [313]:
import numpy as np

In [314]:
# --- 5.2 Columns where blank/none/unknown = true missing (identity/free-text fields) ---
missing_as_null_cols = [
    "funder", "installer", "wpt_name", "subvillage",
    "scheme_name", "scheme_management"
]

for col in missing_as_null_cols:
    before = df[col].isnull().sum()
    cleaned = df[col].astype(str).str.strip()
    is_marker = cleaned.str.lower().isin(text_markers) | df[col].isnull()
    df[col] = df[col].where(~is_marker, np.nan)
    after = df[col].isnull().sum()
    print(f"{col}: {before} -> {after} nulls")

funder: 3637 -> 3668 nulls
installer: 3655 -> 3703 nulls
wpt_name: 2 -> 3588 nulls
subvillage: 371 -> 371 nulls
scheme_name: 28810 -> 28843 nulls
scheme_management: 3878 -> 3878 nulls

In [315]:
# --- Domain-categorical columns: keep "unknown" as a real category, ---
# --- but blank strings still become true nulls ---
categorical_domain_cols = [
    "water_quality", "quality_group", "quantity", "quantity_group",
    "payment", "payment_type", "source", "source_type", "source_class",
    "waterpoint_type", "waterpoint_type_group",
    "extraction_type", "extraction_type_group", "extraction_type_class",
    "management", "management_group"
]

for col in categorical_domain_cols:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].replace("", np.nan)
    df[col] = df[col].replace("nan", np.nan)  # guard against str(NaN) -> "nan"

In [316]:
# ---  Numeric sentinel values acting as disguised nulls ---
# 0 in these fields is not a physically plausible reading -> treat as missing
sentinel_zero_cols = ["gps_height", "longitude", "latitude", "population", "construction_year"]

for col in sentinel_zero_cols:
    zero_count = (df[col] == 0).sum()
    print(f"{col}: {zero_count} zero-value sentinels flagged")

# latitude uses ~-2e-08 as its "zero" due to floating point export quirks
lat_near_zero = df["latitude"].abs() < 1e-6
print(f"latitude near-zero (~-2e-08 placeholder): {lat_near_zero.sum()}")

# amount_tsh == 0 is NOT auto-nulled here — zero payment is a plausible real value
# (free waterpoints exist); flagged for judgment call in Step 12, not Step 5
print(f"\namount_tsh == 0 (left as-is, flagged only): {(df['amount_tsh'] == 0).sum()}")

gps_height: 20438 zero-value sentinels flagged
longitude: 1812 zero-value sentinels flagged
latitude: 0 zero-value sentinels flagged
population: 21381 zero-value sentinels flagged
construction_year: 20709 zero-value sentinels flagged
latitude near-zero (~-2e-08 placeholder): 1812

amount_tsh == 0 (left as-is, flagged only): 41639

In [317]:
((df_raw.isnull().mean()*100).sort_values(ascending=False)).head(7)

scheme_name          48.501684
scheme_management     6.528620
installer             6.153199
funder                6.122896
public_meeting        5.612795
permit                5.144781
subvillage            0.624579
dtype: float64

In [318]:
# --- Sanity check after standardization ---

((df.isnull().mean())*100).sort_values(ascending=False).head(8)

scheme_name          48.557239
scheme_management     6.528620
installer             6.234007
funder                6.175084
wpt_name              6.040404
public_meeting        5.612795
permit                5.144781
subvillage            0.624579
dtype: float64

In [319]:
## Step 6: Fix Data Types

# --- Parse dates ---
df["date_recorded"] = pd.to_datetime(df["date_recorded"], format="%Y-%m-%d", errors="coerce")
print("date_recorded dtype:", df["date_recorded"].dtype)
print("Unparseable dates (now NaT):", df["date_recorded"].isnull().sum())

date_recorded dtype: datetime64[us]
Unparseable dates (now NaT): 0

In [320]:
# ---  IDs and administrative codes as strings, not numeric ---
# These are identifiers/labels, not quantities — arithmetic on them is meaningless
id_and_code_cols = ["id", "region_code", "district_code"]

for col in id_and_code_cols:
    df[col] = df[col].astype("string")
    print(f"{col}: -> {df[col].dtype}")

id: -> string
region_code: -> string
district_code: -> string

In [321]:
# ---  True numeric measurement columns ---
numeric_cols = [
    "amount_tsh", "gps_height", "longitude", "latitude",
    "num_private", "population", "construction_year"
]

for col in numeric_cols:
    before_dtype = df[col].dtype
    df[col] = pd.to_numeric(df[col], errors="coerce")
    new_nulls = df[col].isnull().sum()
    print(f"{col}: {before_dtype} -> {df[col].dtype}, nulls after coercion: {new_nulls}")

amount_tsh: float64 -> float64, nulls after coercion: 0
gps_height: int64 -> int64, nulls after coercion: 0
longitude: float64 -> float64, nulls after coercion: 0
latitude: float64 -> float64, nulls after coercion: 0
num_private: int64 -> int64, nulls after coercion: 0
population: int64 -> int64, nulls after coercion: 0
construction_year: int64 -> int64, nulls after coercion: 0

In [322]:
# --- 6.5 Categorical / label columns -> category dtype ---
categorical_cols = [
    "funder", "installer", "wpt_name", "basin", "subvillage", "region",
    "lga", "ward", "recorded_by", "scheme_management",
    "extraction_type", "extraction_type_group", "extraction_type_class",
    "management", "management_group", "payment", "payment_type",
    "water_quality", "quality_group", "quantity", "quantity_group",
    "source", "source_type", "source_class",
    "waterpoint_type", "waterpoint_type_group"
]

for col in categorical_cols:
    df[col] = df[col].astype("category")

In [323]:
0## Step 7: Re-check Missingness (post type conversion)

# --- 7.1 Missingness snapshot after Step 6 conversions ---
missing_after_dtype_fix = df.isnull().sum()
missing_pct_after = (missing_after_dtype_fix / len(df) * 100).round(2)

missingness_report = pd.DataFrame({
    "missing_count": missing_after_dtype_fix,
    "missing_pct": missing_pct_after
}).sort_values("missing_count", ascending=False)

missingness_report

                       missing_count  missing_pct
scheme_name                    28843        48.56
scheme_management               3878         6.53
installer                       3703         6.23
funder                          3668         6.18
wpt_name                        3588         6.04
public_meeting                  3334         5.61
permit                          3056         5.14
subvillage                       371         0.62
latitude                           0         0.00
longitude                          0         0.00
gps_height                         0         0.00
date_recorded                      0         0.00
id                                 0         0.00
amount_tsh                         0         0.00
num_private                        0         0.00
basin                              0         0.00
lga                                0         0.00
district_code                      0         0.00
region_code                        0         0.00
region                             0         0.00
recorded_by                        0         0.00
population                         0         0.00
ward                               0         0.00
construction_year                  0         0.00
extraction_type                    0         0.00
extraction_type_group              0         0.00
extraction_type_class              0         0.00
management                         0         0.00
management_group                   0         0.00
payment                            0         0.00
payment_type                       0         0.00
water_quality                      0         0.00
quality_group                      0         0.00
quantity                           0         0.00
quantity_group                     0         0.00
source                             0         0.00
source_type                        0         0.00
source_class                       0         0.00
waterpoint_type                    0         0.00
waterpoint_type_group              0         0.00

In [324]:
# --- 7.2 Compare against the raw file's null counts to isolate NEW nulls ---
# df_raw was captured untouched at load time (Step 3)
missing_before = df_raw.isnull().sum()

comparison = pd.DataFrame({
    "missing_before_dtype_fix": missing_before,
    "missing_after_dtype_fix": missing_after_dtype_fix
})
comparison["new_nulls_from_conversion"] = comparison["missing_after_dtype_fix"] - comparison["missing_before_dtype_fix"]

# Only show columns where type conversion actually introduced new nulls
comparison[comparison["new_nulls_from_conversion"] > 0].sort_values(
    "new_nulls_from_conversion", ascending=False
)

,missing_before_dtype_fix,missing_after_dtype_fix,new_nulls_from_conversion
wpt_name,2,3588,3586
installer,3655,3703,48
scheme_name,28810,28843,33
funder,3637,3668,31

In [325]:
# ---  Drill into public_meeting / permit: rows where boolean mapping failed ---
for col in ["public_meeting", "permit"]:
    bad_bool_mask = df[col].isnull() & df_raw[col].notnull()
    print(f"{col}: {bad_bool_mask.sum()} unmapped value(s) -> new nulls")
    if bad_bool_mask.sum() > 0:
        print(df_raw.loc[bad_bool_mask, col].unique())

public_meeting: 0 unmapped value(s) -> new nulls
permit: 0 unmapped value(s) -> new nulls

In [326]:
# ---  Drill into numeric columns: rows where to_numeric coercion failed ---
numeric_cols = ["amount_tsh", "gps_height", "longitude", "latitude",
                 "num_private", "population", "construction_year"]

for col in numeric_cols:
    bad_numeric_mask = df[col].isnull() & df_raw[col].notnull()
    n_bad = bad_numeric_mask.sum()
    if n_bad > 0:
        print(f"{col}: {n_bad} unparseable value(s)")
        print(df_raw.loc[bad_numeric_mask, col].unique())

In [327]:
# ---  Sanity gate: fail loudly if conversion silently nulled a large chunk of a column ---
THRESHOLD_PCT = 5.0  # flag anything that lost more than 5% of its data to bad conversion

flagged = comparison[comparison["new_nulls_from_conversion"] > 0].copy()
flagged["new_null_pct"] = (flagged["new_nulls_from_conversion"] / len(df) * 100).round(2)
risky = flagged[flagged["new_null_pct"] > THRESHOLD_PCT]

if not risky.empty:
    print(" Columns with significant new nulls from type conversion — investigate before proceeding:")
    print(risky)
else:
    print("No column lost more than", THRESHOLD_PCT, "% of its data to type-conversion nulls.")

 Columns with significant new nulls from type conversion — investigate before proceeding:
          missing_before_dtype_fix  missing_after_dtype_fix  \
wpt_name                         2                     3588

          new_nulls_from_conversion  new_null_pct
wpt_name                       3586          6.04

In [328]:
##  Handle Missing Values

# ---  Confirm current missingness landscape before deciding treatment ---
missing_summary = df.isnull().sum()
missing_pct = (missing_summary / len(df) * 100).round(2)
pd.DataFrame({
    "missing_count": missing_summary,
    "missing_pct": missing_pct
}).query("missing_count > 0").sort_values("missing_count", ascending=False)

                   missing_count  missing_pct
scheme_name                28843        48.56
scheme_management           3878         6.53
installer                   3703         6.23
funder                      3668         6.18
wpt_name                    3588         6.04
public_meeting              3334         5.61
permit                      3056         5.14
subvillage                   371         0.62

In [329]:
# Drop scheme_name: redundant with scheme_management/management/management_group,
# and ~48% missing on top of that
redundant_cols_to_drop = ["scheme_name"]

df = df.drop(columns=redundant_cols_to_drop)

In [330]:
df.shape

(59400, 39)

In [331]:
df.dtypes

id                               string
amount_tsh                      float64
date_recorded            datetime64[us]
funder                         category
gps_height                        int64
installer                      category
longitude                       float64
latitude                        float64
wpt_name                       category
num_private                       int64
basin                          category
subvillage                     category
region                         category
region_code                      string
district_code                    string
lga                            category
ward                           category
population                        int64
public_meeting                   object
recorded_by                    category
scheme_management              category
permit                           object
construction_year                 int64
extraction_type                category
extraction_type_group          category
extraction_type_class          category
management                     category
management_group               category
payment                        category
payment_type                   category
water_quality                  category
quality_group                  category
quantity                       category
quantity_group                 category
source                         category
source_type                    category
source_class                   category
waterpoint_type                category
waterpoint_type_group          category
dtype: object

In [332]:
# scheme_management: 6.5% missing, not redundant with `management`
# (similar categories but different counts — distinct signal, worth keeping)
# indicator flag — preserve the fact that it was originally missing
df["scheme_management_was_missing"] = df["scheme_management"].isnull()

# explicit "missing" label rather than leaving NaN
df["scheme_management"] = df["scheme_management"].cat.add_categories(["missing"])
df["scheme_management"] = df["scheme_management"].fillna("missing")

In [333]:
# installer: 6.2% true missing, PLUS a disguised-missing sentinel:
# "0" appears 777 times as a literal string, not a real installer name
df["installer"] = df["installer"].replace("0", pd.NA)

df["installer"] = df["installer"].astype("category")

# indicator flag — covers both real NaN and the "0" sentinel folded in above
df["installer_was_missing"] = df["installer"].isnull()

# explicit "missing" label
df["installer"] = df["installer"].cat.add_categories(["missing"])
df["installer"] = df["installer"].fillna("missing")

In [334]:
# funder: 6.1% true missing, PLUS the same "0" sentinel seen in installer
# (confirmed: same 777 rows have "0" in both funder and installer —
# likely the same surveyor leaving both blank at once)
df["funder"] = df["funder"].replace("0", pd.NA)

df["funder"] = df["funder"].astype("category")

# indicator flag — covers both real NaN and the "0" sentinel folded in above
df["funder_was_missing"] = df["funder"].isnull()

# explicit "missing" label
df["funder"] = df["funder"].cat.add_categories(["missing"])
df["funder"] = df["funder"].fillna("missing")

In [335]:
# wpt_name: Step 5 already converted "none"/"unknown"/etc. to real NaN.
# Step 8's only job here is the indicator flag + explicit "missing" label —
# no marker cleanup needed again.
df["wpt_name"] = df["wpt_name"].astype("category")

df["wpt_name_was_missing"] = df["wpt_name"].isnull()

df["wpt_name"] = df["wpt_name"].cat.add_categories(["missing"])
df["wpt_name"] = df["wpt_name"].fillna("missing")

In [336]:
df["public_meeting"] = df["public_meeting"].astype("object")

In [337]:
df["public_meeting"].unique()

array([True, nan, False], dtype=object)

In [338]:
df["public_meeting"].value_counts(dropna=False)

public_meeting
True     51011
False     5055
NaN       3334
Name: count, dtype: int64

In [339]:
df["public_meeting"] = df["public_meeting"].fillna("unknown")
df["public_meeting"].value_counts(dropna=False)

public_meeting
True       51011
False       5055
unknown     3334
Name: count, dtype: int64

In [340]:

df["permit"] = df["permit"].astype("object")
df["permit"] = df["permit"].fillna("unknown")
df["public_meeting"].value_counts(dropna=False)


# subvillage: 0.62% missing, no disguised markers found. High-cardinality
# free-text location detail (19k+ unique, like wpt_name) — no Step 10
# standardization planned for this one either.
df["subvillage"] = df["subvillage"].astype("category")
df["subvillage_was_missing"] = df["subvillage"].isnull()
df["subvillage"] = df["subvillage"].cat.add_categories(["missing"])
df["subvillage"] = df["subvillage"].fillna("missing")

In [341]:
# Save Phase 1 (Steps 1–9) processed data to Desktop
import os

desktop_path = os.path.join(os.path.expanduser("~"), "Desktop", "processed_data_phase1.csv")
df.to_csv(desktop_path, index=False)

print(f"Saved to: {desktop_path}")
print(f"Shape: {df.shape}")

Saved to: C:\Users\HomePC\Desktop\processed_data_phase1.csv
Shape: (59400, 44)

In [342]:
from IPython.display import display, HTML

display(HTML("""
<h1 style="text-align:center; color:green; font-size:90px;">
     END OF PHASE 1: CLEANING 
</h1>
"""))