In [5]:
import pandas as pd
df= pd.read_csv(r"C:\Users\HomePC\Desktop\house-prices-advanced-regression-techniques\train.csv")

In [4]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [7]:
for i , column in enumerate (df.columns, start=0):
    print (f"{i}.{column}")

0.Id
1.MSSubClass
2.MSZoning
3.LotFrontage
4.LotArea
5.Street
6.Alley
7.LotShape
8.LandContour
9.Utilities
10.LotConfig
11.LandSlope
12.Neighborhood
13.Condition1
14.Condition2
15.BldgType
16.HouseStyle
17.OverallQual
18.OverallCond
19.YearBuilt
20.YearRemodAdd
21.RoofStyle
22.RoofMatl
23.Exterior1st
24.Exterior2nd
25.MasVnrType
26.MasVnrArea
27.ExterQual
28.ExterCond
29.Foundation
30.BsmtQual
31.BsmtCond
32.BsmtExposure
33.BsmtFinType1
34.BsmtFinSF1
35.BsmtFinType2
36.BsmtFinSF2
37.BsmtUnfSF
38.TotalBsmtSF
39.Heating
40.HeatingQC
41.CentralAir
42.Electrical
43.1stFlrSF
44.2ndFlrSF
45.LowQualFinSF
46.GrLivArea
47.BsmtFullBath
48.BsmtHalfBath
49.FullBath
50.HalfBath
51.BedroomAbvGr
52.KitchenAbvGr
53.KitchenQual
54.TotRmsAbvGrd
55.Functional
56.Fireplaces
57.FireplaceQu
58.GarageType
59.GarageYrBlt
60.GarageFinish
61.GarageCars
62.GarageArea
63.GarageQual
64.GarageCond
65.PavedDrive
66.WoodDeckSF
67.OpenPorchSF
68.EnclosedPorch
69.3SsnPorch
70.ScreenPorch
71.PoolArea
72.PoolQC
73.Fence
74.MiscFeature
75.MiscVal
76.MoSold
77.YrSold
78.SaleType
79.SaleCondition
80.SalePrice

In [8]:
df["SalePrice"]

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [11]:
df[["SaleCondition" ,"KitchenQual","SalePrice"]]

     SaleCondition KitchenQual  SalePrice
0           Normal          Gd     208500
1           Normal          TA     181500
2           Normal          Gd     223500
3          Abnorml          Gd     140000
4           Normal          Gd     250000
...            ...         ...        ...
1455        Normal          TA     175000
1456        Normal          TA     210000
1457        Normal          Gd     266500
1458        Normal          Gd     142125
1459        Normal          TA     147500

[1460 rows x 3 columns]

In [19]:
 df.iloc[1:7, [2, 78, 80]]

  MSZoning SaleType  SalePrice
1       RL       WD     181500
2       RL       WD     223500
3       RL       WD     140000
4       RL       WD     250000
5       RL       WD     143000
6       RL       WD     307000

In [13]:
#Sort homes by sale price, highest first
df.sort_values("SalePrice", ascending= False).head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
691,692,60,RL,104.0,21535,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2007,WD,Normal,755000
1182,1183,60,RL,160.0,15623,Pave,NaN,IR1,Lvl,AllPub,...,555,Ex,MnPrv,NaN,0,7,2007,WD,Abnorml,745000
1169,1170,60,RL,118.0,35760,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,625000
898,899,20,RL,100.0,12919,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,3,2010,New,Partial,611657
803,804,60,RL,107.0,13891,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2009,New,Partial,582933
1046,1047,60,RL,85.0,16056,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,New,Partial,556581
440,441,20,RL,105.0,15431,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,555000
769,770,60,RL,47.0,53504,Pave,NaN,IR2,HLS,AllPub,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,538000
178,179,20,RL,63.0,17423,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,New,Partial,501837
798,799,60,RL,104.0,13518,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,New,Partial,485000

In [14]:
max(["SalePrice"])

'SalePrice'

In [15]:
df.sort_values(
    by=["Neighborhood", "SalePrice"],
    ascending=[True, False]
).head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
639,640,120,RL,53.0,3982,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2006,New,Partial,264561
1394,1395,120,RL,53.0,4045,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2006,New,Partial,246578
559,560,120,RL,NaN,3196,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2006,WD,Normal,234000
851,852,120,RL,NaN,3196,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,215000
1019,1020,120,RL,43.0,3013,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,213490
597,598,120,RL,53.0,3922,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2007,New,Partial,194201
229,230,120,RL,43.0,3182,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,192500
385,386,120,RL,43.0,3182,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,192000
1023,1024,120,RL,43.0,3182,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,191000
1004,1005,120,RL,43.0,3182,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,181000

In [20]:
#Filtering 
# Select homes above a price threshold
ExpensiveHomes=df[df["SalePrice"]> 300000]
print(ExpensiveHomes)

        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
6        7          20       RL         75.0    10084   Pave   NaN      Reg
11      12          60       RL         85.0    11924   Pave   NaN      IR1
20      21          60       RL        101.0    14215   Pave   NaN      IR1
27      28          20       RL         98.0    11478   Pave   NaN      Reg
35      36          60       RL        108.0    13418   Pave   NaN      Reg
...    ...         ...      ...          ...      ...    ...   ...      ...
1373  1374          20       RL          NaN    11400   Pave   NaN      Reg
1388  1389          20       RL         42.0    14892   Pave   NaN      IR1
1417  1418          60       RL          NaN    16545   Pave   NaN      IR1
1437  1438          20       RL         96.0    12444   Pave   NaN      Reg
1442  1443          60       FV         85.0    11003   Pave   NaN      Reg

     LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal  \
6            Lvl    AllPub  ...        0    NaN   NaN         NaN       0
11           Lvl    AllPub  ...        0    NaN   NaN         NaN       0
20           Lvl    AllPub  ...        0    NaN   NaN         NaN       0
27           Lvl    AllPub  ...        0    NaN   NaN         NaN       0
35           Lvl    AllPub  ...        0    NaN   NaN         NaN       0
...          ...       ...  ...      ...    ...   ...         ...     ...
1373         Lvl    AllPub  ...        0    NaN   NaN         NaN       0
1388         HLS    AllPub  ...        0    NaN   NaN         NaN       0
1417         Lvl    AllPub  ...        0    NaN   NaN         NaN       0
1437         Lvl    AllPub  ...        0    NaN   NaN         NaN       0
1442         Lvl    AllPub  ...        0    NaN   NaN         NaN       0

     MoSold YrSold  SaleType  SaleCondition  SalePrice
6         8   2007        WD         Normal     307000
11        7   2006       New        Partial     345000
20       11   2006       New        Partial     325300
27        5   2010        WD         Normal     306000
35        9   2006        WD         Normal     309000
...     ...    ...       ...            ...        ...
1373      3   2007        WD         Normal     466500
1388     10   2009        WD         Normal     377500
1417      5   2009        WD         Normal     340000
1437     11   2008       New        Partial     394617
1442      4   2009        WD         Normal     310000

[115 rows x 81 columns]

In [22]:
##Combine conditions using & (and) and | (or). Parentheses matte##
modern_large_homes = df[
    (df["YearBuilt"] >= 2000) &
    (df["GrLivArea"] > 2000)
]
print(modern_large_homes)

        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
4        5          60       RL         84.0    14260   Pave   NaN      IR1
11      12          60       RL         85.0    11924   Pave   NaN      IR1
20      21          60       RL        101.0    14215   Pave   NaN      IR1
35      36          60       RL        108.0    13418   Pave   NaN      Reg
46      47          50       RL         48.0    12822   Pave   NaN      IR1
...    ...         ...      ...          ...      ...    ...   ...      ...
1298  1299          60       RL        313.0    63887   Pave   NaN      IR3
1342  1343          60       RL          NaN     9375   Pave   NaN      Reg
1373  1374          20       RL          NaN    11400   Pave   NaN      Reg
1395  1396          60       RL         88.0    12665   Pave   NaN      IR1
1442  1443          60       FV         85.0    11003   Pave   NaN      Reg

     LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal  \
4            Lvl    AllPub  ...        0    NaN   NaN         NaN       0
11           Lvl    AllPub  ...        0    NaN   NaN         NaN       0
20           Lvl    AllPub  ...        0    NaN   NaN         NaN       0
35           Lvl    AllPub  ...        0    NaN   NaN         NaN       0
46           Lvl    AllPub  ...        0    NaN   NaN         NaN       0
...          ...       ...  ...      ...    ...   ...         ...     ...
1298         Bnk    AllPub  ...      480     Gd   NaN         NaN       0
1342         Lvl    AllPub  ...        0    NaN   NaN         NaN       0
1373         Lvl    AllPub  ...        0    NaN   NaN         NaN       0
1395         Lvl    AllPub  ...        0    NaN   NaN         NaN       0
1442         Lvl    AllPub  ...        0    NaN   NaN         NaN       0

     MoSold YrSold  SaleType  SaleCondition  SalePrice
4        12   2008        WD         Normal     250000
11        7   2006       New        Partial     345000
20       11   2006       New        Partial     325300
35        9   2006        WD         Normal     309000
46        8   2009        WD        Abnorml     239686
...     ...    ...       ...            ...        ...
1298      1   2008       New        Partial     160000
1342      8   2007        WD         Normal     228500
1373      3   2007        WD         Normal     466500
1395      2   2007        WD         Normal     281213
1442      4   2009        WD         Normal     310000

[68 rows x 81 columns]

In [24]:
##Find homes in selected neighbourhoods##
chosen_areas = df[df["Neighborhood"].isin(["NridgHt", "NoRidge", "StoneBr"])]
print(chosen_areas)

        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
4        5          60       RL         84.0    14260   Pave   NaN      IR1
11      12          60       RL         85.0    11924   Pave   NaN      IR1
20      21          60       RL        101.0    14215   Pave   NaN      IR1
25      26          20       RL        110.0    14230   Pave   NaN      Reg
27      28          20       RL         98.0    11478   Pave   NaN      Reg
...    ...         ...      ...          ...      ...    ...   ...      ...
1361  1362          20       RL        124.0    16158   Pave   NaN      IR1
1373  1374          20       RL          NaN    11400   Pave   NaN      Reg
1417  1418          60       RL          NaN    16545   Pave   NaN      IR1
1426  1427          60       RL         81.0    10944   Pave   NaN      IR1
1437  1438          20       RL         96.0    12444   Pave   NaN      Reg

     LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal  \
4            Lvl    AllPub  ...        0    NaN   NaN         NaN       0
11           Lvl    AllPub  ...        0    NaN   NaN         NaN       0
20           Lvl    AllPub  ...        0    NaN   NaN         NaN       0
25           Lvl    AllPub  ...        0    NaN   NaN         NaN       0
27           Lvl    AllPub  ...        0    NaN   NaN         NaN       0
...          ...       ...  ...      ...    ...   ...         ...     ...
1361         Low    AllPub  ...        0    NaN   NaN         NaN       0
1373         Lvl    AllPub  ...        0    NaN   NaN         NaN       0
1417         Lvl    AllPub  ...        0    NaN   NaN         NaN       0
1426         Lvl    AllPub  ...        0    NaN   NaN         NaN       0
1437         Lvl    AllPub  ...        0    NaN   NaN         NaN       0

     MoSold YrSold  SaleType  SaleCondition  SalePrice
4        12   2008        WD         Normal     250000
11        7   2006       New        Partial     345000
20       11   2006       New        Partial     325300
25        7   2009        WD         Normal     256300
27        5   2010        WD         Normal     306000
...     ...    ...       ...            ...        ...
1361      6   2009        WD         Normal     260000
1373      3   2007        WD         Normal     466500
1417      5   2009        WD         Normal     340000
1426      8   2008        WD         Normal     271000
1437     11   2008       New        Partial     394617

[143 rows x 81 columns]

In [25]:
##Find missing values in a column
df[df["LotFrontage"].isna()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
12,13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,144000
14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2008,WD,Normal,157000
16,17,20,RL,NaN,11241,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,700,3,2010,WD,Normal,149000
24,25,20,RL,NaN,8246,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2010,WD,Normal,154000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,1430,20,RL,NaN,12546,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2007,WD,Normal,182900
1431,1432,120,RL,NaN,4928,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,143750
1441,1442,120,RM,NaN,4426,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,149300
1443,1444,30,RL,NaN,8854,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,121000
1446,1447,20,RL,NaN,26142,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,157900

In [26]:
## Aggregating
#### Use .agg() when you want several summary statistics at once
neighborhood_summary = (
    df.groupby("Neighborhood")
      .agg(
          homes_sold=("SalePrice", "count"),
          average_price=("SalePrice", "mean"),
          median_price=("SalePrice", "median"),
          highest_price=("SalePrice", "max"),
          average_living_area=("GrLivArea", "mean")
      )
      .sort_values("average_price", ascending=False)
)

neighborhood_summary.head(10)

,homes_sold,average_price,median_price,highest_price,average_living_area
Neighborhood,,,,,
NoRidge,41,335295.317073,301500.0,755000,2508.853659
NridgHt,77,316270.623377,315000.0,611657,1915.948052
StoneBr,25,310499.000000,278000.0,556581,1879.080000
Timber,38,242247.447368,228475.0,378500,1749.368421
Veenker,11,238772.727273,218000.0,385000,1539.636364
Somerst,86,225379.837209,225500.0,423000,1596.651163
ClearCr,28,212565.428571,200250.0,328000,1788.107143
Crawfor,51,210624.725490,200624.0,392500,1791.607843
CollgCr,150,197965.773333,197200.0,424870,1480.500000
Blmngtn,17,194870.882353,191000.0,264561,1427.941176

In [1]:
import os
os.getcwd()

'C:\\Users\\HomePC'